name: bmad-project-analyst
version: 0.1.0
short-title: bmad-project-analyst
description: "An agent that analyzes Java web projects to identify inconsistent code styles and specifications, then generates a set of AI guidelines to help AI-powered tools produce code that conforms to project norms."
